__author__ = 'ivar'

from melody import makeMelodyWav, n

notes = [
    n("E", d=4),
    n("D#", d=1),
    n("E"),
    n("D#"),
    n("E"),
    n("B", 3),
    n("D", 4),
    n("C"),
    n("A", 3, 3),
    n("E", d=1),
    n("G#"),
    n("A"),
    n("B", 3, 3),
    n("E", d=1),
    n("G#"),
    n("B"),
    n("C", 4, 3),
    n("E", 3, 1),
    n("E", 4),
    n("D#"),
    n("E"),
    n("D#"),
    n("E"),
    n("B", 3),
    n("D", 4),
    n("C"),
    n("A", 3, 3),
    n("E", d=1),
    n("G#"),
    n("A"),
    n("B", d=3),
    n("E", d=1),
    n("C", 4),
    n("B", 3),
    n("A", d=3),

    n("A", 2, 1, 8, 0.4),
    n("C", 3),
    n("E", d=4),
    n("G#", 2, 1),
    n("C", 3),
    n("E", d=4),
    n("A", 2, 1),
    n("C", 3),
    n("E"),

    n("A", 2, 1, 32),
    n("C", 3),
    n("E", d=4),
    n("G#", 2, 1),
    n("C", 3),
    n("E", d=4),
    n("A", 2, 1),
    n("C", 3),
    n("E"),

]

makeMelodyWav("elise2.wav", 240, notes)
